# Generated by Django 4.2.5 on 2023-09-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="feedback_from_user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f1", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="home_rent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("home_img", models.ImageField(upload_to="static/images/")),
                ("img_2", models.ImageField(default="", upload_to="static/images")),
                ("img_3", models.ImageField(default="", upload_to="static/images/")),
                ("img_4", models.ImageField(default="", upload_to="static/images")),
                ("img_5", models.ImageField(default="", upload_to="static/images/")),
                ("home_price", models.IntegerField()),
                ("home_desc", models.CharField(max_length=500)),
                ("location", models.CharField(max_length=100)),
                ("home_address", models.CharField(max_length=500)),
                ("home_type", models.CharField(max_length=50)),
            ],
        ),
    ]
